// 운영 전 확인 사항
// - 아래 데이터는 MVP 실행용 샘플입니다.
// - 가격, 영업시간, 실제 거리, 단체 가능 여부는 직접 확인 후 수정하세요.
// - GitHub Pages 정적 웹앱에서 바로 쓰기 위해 window.RESTAURANTS 형태로 분리했습니다.

window.RESTAURANTS_META = {
  source: "sample-manual",
  baseName: "대신파이낸스센터",
  baseAddress: "서울 중구 삼일대로 343",
  baseLat: 37.5651225406354,
  baseLon: 126.987055821012,
  radiusMeters: 400,
  generatedAt: null,
  count: null,
  notice: "초기 샘플 데이터입니다. GitHub Actions에서 네이버 지역검색 API를 실행하면 자동 갱신됩니다."
};

window.RESTAURANTS = [
  {
    id: "abiko-daishin-b1",
    name: "아비꼬 대신증권점",
    category: "카레/일식",
    mainMenu: "카레, 카레우동",
    recommendedMenu: "카레우동 세트",
    lunchPrice: 12000,
    dinnerPrice: 14000,
    distanceMeters: 40,
    walkMinutes: 1,
    tags: ["건물내", "빠른점심", "혼밥", "무난함"],
    goodForLunch: true,
    goodForDinner: false,
    groupFriendly: true,
    alcoholFriendly: false,
    managerPreferenceScore: 4,
    notes: "대신파이낸스센터 B1 푸드코트권. 각자 메뉴 선택이 쉬운 점심용.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "hanok-bibimbap-myeongdong",
    name: "한옥마을 비빔밥 대신파이낸스센터 명동점",
    category: "한식/비빔밥",
    mainMenu: "전주비빔밥, 돌솥비빔밥, 콩나물국밥",
    recommendedMenu: "돌솥비빔밥 또는 콩나물국밥",
    lunchPrice: 13000,
    dinnerPrice: 16000,
    distanceMeters: 50,
    walkMinutes: 1,
    tags: ["건물내", "한식", "깔끔함", "팀장님취향"],
    goodForLunch: true,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: false,
    managerPreferenceScore: 9,
    notes: "한식 반상류라 연령대가 섞인 팀 점심에 안정적.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "misik-hoegwan-b1",
    name: "미식회관 명동 대신파이낸스센터점",
    category: "한식/국탕류",
    mainMenu: "비빔밥, 국탕류",
    recommendedMenu: "국탕류 한상",
    lunchPrice: 12000,
    dinnerPrice: 15000,
    distanceMeters: 55,
    walkMinutes: 1,
    tags: ["건물내", "한식", "국탕류", "가성비"],
    goodForLunch: true,
    goodForDinner: false,
    groupFriendly: true,
    alcoholFriendly: false,
    managerPreferenceScore: 9,
    notes: "국밥/찌개류 선호가 있는 팀장님 취향 반영용 샘플.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "golden-kitchen-b1",
    name: "골든키친",
    category: "덮밥/퓨전한식",
    mainMenu: "덮밥, 연어아보카도밥",
    recommendedMenu: "연어아보카도밥",
    lunchPrice: 13000,
    dinnerPrice: 15000,
    distanceMeters: 60,
    walkMinutes: 1,
    tags: ["건물내", "깔끔함", "가벼운점심", "여직원선호가능"],
    goodForLunch: true,
    goodForDinner: false,
    groupFriendly: true,
    alcoholFriendly: false,
    managerPreferenceScore: 5,
    notes: "무거운 국밥류가 부담스러운 날 대안.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "yubunam-b1-sample",
    name: "유부남집",
    category: "분식/유부초밥",
    mainMenu: "유부초밥, 우동, 간단세트",
    recommendedMenu: "유부초밥+우동 세트",
    lunchPrice: 11000,
    dinnerPrice: 13000,
    distanceMeters: 65,
    walkMinutes: 1,
    tags: ["건물내", "빠른점심", "가벼움", "분식"],
    goodForLunch: true,
    goodForDinner: false,
    groupFriendly: true,
    alcoholFriendly: false,
    managerPreferenceScore: 3,
    notes: "가볍게 먹고 싶은 날. 실제 매장명/메뉴는 확인 후 수정 권장.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "myeongdong-kalguksu-sundubu",
    name: "명동칼국수 순두부 부대찌개",
    category: "한식/전골",
    mainMenu: "칼국수, 순두부, 부대찌개, 만두전골",
    recommendedMenu: "순두부찌개 또는 만두전골",
    lunchPrice: 12000,
    dinnerPrice: 22000,
    distanceMeters: 260,
    walkMinutes: 4,
    tags: ["한식", "찌개", "전골", "팀장님취향", "따뜻한메뉴"],
    goodForLunch: true,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: true,
    managerPreferenceScore: 10,
    notes: "순두부/부대찌개류라 팀장님 취향과 잘 맞는 샘플.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "euljiro-meat-house-sample",
    name: "을지로 고기집 샘플",
    category: "고기/회식",
    mainMenu: "삼겹살, 목살, 된장찌개",
    recommendedMenu: "삼겹살+목살 세트",
    lunchPrice: 15000,
    dinnerPrice: 28000,
    distanceMeters: 320,
    walkMinutes: 5,
    tags: ["고기", "회식", "술한잔", "단체"],
    goodForLunch: false,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: true,
    managerPreferenceScore: 7,
    notes: "저녁 회식용 샘플. 실제 가게명으로 교체하세요.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "clean-japanese-sample",
    name: "깔끔한 일식집 샘플",
    category: "일식/정식",
    mainMenu: "돈카츠, 사케동, 정식",
    recommendedMenu: "돈카츠 정식",
    lunchPrice: 14000,
    dinnerPrice: 23000,
    distanceMeters: 350,
    walkMinutes: 6,
    tags: ["깔끔함", "조용한식사", "정식", "무난함"],
    goodForLunch: true,
    goodForDinner: true,
    groupFriendly: false,
    alcoholFriendly: false,
    managerPreferenceScore: 5,
    notes: "한식이 연속될 때 분위기 전환용 샘플.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "chinese-lunch-sample",
    name: "중식당 샘플",
    category: "중식",
    mainMenu: "짜장면, 짬뽕, 탕수육, 볶음밥",
    recommendedMenu: "짬뽕밥 또는 탕수육 세트",
    lunchPrice: 11000,
    dinnerPrice: 24000,
    distanceMeters: 370,
    walkMinutes: 6,
    tags: ["중식", "빠른점심", "가성비", "단체"],
    goodForLunch: true,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: true,
    managerPreferenceScore: 5,
    notes: "메뉴 호불호가 적고 빠른 점심 후보.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "soup-rice-sample",
    name: "국밥집 샘플",
    category: "국밥/순대국",
    mainMenu: "순대국, 돼지국밥, 수육",
    recommendedMenu: "순대국 정식",
    lunchPrice: 11000,
    dinnerPrice: 23000,
    distanceMeters: 390,
    walkMinutes: 7,
    tags: ["국밥", "한식", "팀장님취향", "든든함", "술한잔"],
    goodForLunch: true,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: true,
    managerPreferenceScore: 10,
    notes: "팀장님 선호 메뉴 최우선 반영용 샘플. 실제 식당으로 교체 권장.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "quiet-korean-table-sample",
    name: "깔끔한 한식 반상 샘플",
    category: "한식/백반",
    mainMenu: "생선구이, 제육, 된장찌개",
    recommendedMenu: "고등어구이+된장찌개 반상",
    lunchPrice: 13000,
    dinnerPrice: 19000,
    distanceMeters: 280,
    walkMinutes: 5,
    tags: ["한식", "백반", "깔끔함", "조용한식사", "팀장님취향"],
    goodForLunch: true,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: false,
    managerPreferenceScore: 9,
    notes: "연령대가 섞인 팀 점심에 안정적인 후보.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  },
  {
    id: "premium-korean-dinner-sample",
    name: "프리미엄 한식 회식 샘플",
    category: "한식/회식",
    mainMenu: "갈비찜, 불고기, 전골",
    recommendedMenu: "불고기 전골 코스",
    lunchPrice: 18000,
    dinnerPrice: 35000,
    distanceMeters: 400,
    walkMinutes: 7,
    tags: ["한식", "회식", "깔끔함", "단체", "조용한식사"],
    goodForLunch: false,
    goodForDinner: true,
    groupFriendly: true,
    alcoholFriendly: true,
    managerPreferenceScore: 8,
    notes: "조용하고 깔끔한 회식 후보. 실제 예약 가능 여부 확인 필요.",
    lastVisitedDate: null,
    dislike: false,
    favorite: false
  }
];
