// 자동 생성 파일입니다. scripts/fetch_naver_restaurants.py가 갱신합니다.
// 수동 수정이 필요하면 naver-query-config.json의 manualOverrides를 우선 사용하세요.

window.RESTAURANTS_META = {
  "source": "naver-local-search",
  "baseName": "대신파이낸스센터",
  "baseAddress": "서울 중구 삼일대로 343",
  "baseLat": 37.5651225406354,
  "baseLon": 126.987055821012,
  "radiusMeters": 400,
  "queries": [
    "대신파이낸스센터 점심",
    "대신파이낸스센터 맛집",
    "대신파이낸스센터 한식",
    "대신파이낸스센터 국밥",
    "대신파이낸스센터 순두부",
    "을지로입구역 점심",
    "을지로입구역 한식",
    "을지로입구역 국밥",
    "을지로입구역 중식",
    "을지로입구역 일식",
    "을지로입구역 회식",
    "명동 점심 맛집",
    "명동 한식 점심",
    "명동 회식 고기"
  ],
  "errors": [],
  "notice": "가격·메뉴·단체 가능 여부는 네이버 지역검색 카테고리 기반 추정값입니다. 운영 전 확인하세요.",
  "generatedAt": "2026-07-06T23:36:52+09:00",
  "count": 22
};

window.RESTAURANTS = [
  {
    "id": "naver-restaurant-40e7ad74",
    "name": "박가네고등어 명동대신파이낸스센터점",
    "category": "한식",
    "mainMenu": "음식점>한식",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 2,
    "walkMinutes": 1,
    "tags": [
      "건물근처",
      "빠른점심",
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "",
    "roadAddress": "서울특별시 중구 삼일대로 343 지하1층",
    "address": "서울특별시 중구 저동1가 114 지하1층",
    "lat": 37.5651208,
    "lon": 126.9870758
  },
  {
    "id": "naver-restaurant-e497eaac",
    "name": "다이닝원 명동점",
    "category": "일식/돈까스",
    "mainMenu": "음식점>일식,초밥뷔페",
    "recommendedMenu": "덮밥 또는 우동",
    "lunchPrice": 16000,
    "dinnerPrice": 30000,
    "distanceMeters": 182,
    "walkMinutes": 2,
    "tags": [
      "깔끔함"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 5,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "",
    "roadAddress": "서울특별시 중구 명동길 55 4층",
    "address": "서울특별시 중구 명동1가 7-1 4층",
    "lat": 37.5641454,
    "lon": 126.9854055
  },
  {
    "id": "naver-restaurant-9be4a442",
    "name": "난로은회 을지로",
    "category": "한식",
    "mainMenu": "한식>육류,고기요리",
    "recommendedMenu": "고기류 식사",
    "lunchPrice": 16000,
    "dinnerPrice": 30000,
    "distanceMeters": 184,
    "walkMinutes": 2,
    "tags": [
      "술한잔",
      "팀장님취향",
      "한식",
      "회식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": true,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://app.catchtable.co.kr/ct/shop/nanroeunhoi_euljiro",
    "roadAddress": "서울특별시 중구 을지로 100 파인에비뉴 B동 지하1층",
    "address": "서울특별시 중구 을지로2가 203 파인에비뉴 B동 지하1층",
    "lat": 37.5658847,
    "lon": 126.9889089
  },
  {
    "id": "naver-restaurant-bf7d24d7",
    "name": "하동관 명동본점",
    "category": "한식/국탕류",
    "mainMenu": "한식>곰탕,설렁탕",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 199,
    "walkMinutes": 3,
    "tags": [
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "http://www.hadongkwan.co.kr",
    "roadAddress": "서울특별시 중구 명동9길 12",
    "address": "서울특별시 중구 명동1가 10-4",
    "lat": 37.5644272,
    "lon": 126.9849722
  },
  {
    "id": "naver-restaurant-9cac5a67",
    "name": "장인닭갈비 명동점",
    "category": "한식",
    "mainMenu": "한식>닭갈비",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 16000,
    "dinnerPrice": 30000,
    "distanceMeters": 209,
    "walkMinutes": 3,
    "tags": [
      "술한잔",
      "팀장님취향",
      "한식",
      "회식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": true,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://jangindak.co.kr/",
    "roadAddress": "서울특별시 중구 명동9길 15 1층",
    "address": "서울특별시 중구 명동1가 36-3 1층",
    "lat": 37.5645425,
    "lon": 126.9847957
  },
  {
    "id": "naver-restaurant-c1487acb",
    "name": "남영동양문 을지로점",
    "category": "한식",
    "mainMenu": "음식점>한식>육류,고기요리",
    "recommendedMenu": "고기류 식사",
    "lunchPrice": 16000,
    "dinnerPrice": 30000,
    "distanceMeters": 246,
    "walkMinutes": 3,
    "tags": [
      "술한잔",
      "팀장님취향",
      "한식",
      "회식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": true,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://go.catchtable.co.kr/s6w7e4",
    "roadAddress": "서울특별시 중구 수표로 43 1층 남영동양문 을지로점",
    "address": "서울특별시 중구 저동2가 76-6 1층 남영동양문 을지로점",
    "lat": 37.565035,
    "lon": 126.989842
  },
  {
    "id": "naver-1-3c5504ca",
    "name": "명동교자 1호점",
    "category": "한식",
    "mainMenu": "한식>칼국수,만두",
    "recommendedMenu": "칼국수와 만두",
    "lunchPrice": 11000,
    "dinnerPrice": 16000,
    "distanceMeters": 247,
    "walkMinutes": 3,
    "tags": [
      "가성비",
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "http://www.mdkj.co.kr/",
    "roadAddress": "서울특별시 중구 명동10길 10 명동교자",
    "address": "서울특별시 중구 명동2가 33-4 명동교자",
    "lat": 37.5634828,
    "lon": 126.9851666
  },
  {
    "id": "naver-restaurant-17362307",
    "name": "맥도날드 명동점",
    "category": "햄버거",
    "mainMenu": "양식>햄버거",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 248,
    "walkMinutes": 3,
    "tags": [],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 4,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://www.mcdonalds.co.kr/",
    "roadAddress": "서울특별시 중구 명동7길 8",
    "address": "서울특별시 중구 명동1가 48-2",
    "lat": 37.5641571,
    "lon": 126.9845147
  },
  {
    "id": "naver-3-b6ce3118",
    "name": "청와옥 을지로3가직영점",
    "category": "한식/국탕류",
    "mainMenu": "음식점>한식>육류,고기요리>순대,순댓국",
    "recommendedMenu": "순대국",
    "lunchPrice": 11000,
    "dinnerPrice": 16000,
    "distanceMeters": 286,
    "walkMinutes": 4,
    "tags": [
      "가성비",
      "술한잔",
      "팀장님취향",
      "한식",
      "회식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": true,
    "managerPreferenceScore": 10,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://www.instagram.com/cheongwaok/",
    "roadAddress": "서울특별시 중구 을지로 110 1층 1호",
    "address": "서울특별시 중구 을지로3가 346-1 1층 1호",
    "lat": 37.5660827,
    "lon": 126.9900656
  },
  {
    "id": "naver-restaurant-56838e61",
    "name": "미성옥",
    "category": "한식/국탕류",
    "mainMenu": "한식>곰탕,설렁탕",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 292,
    "walkMinutes": 4,
    "tags": [
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "",
    "roadAddress": "서울특별시 중구 명동길 25-11",
    "address": "서울특별시 중구 명동1가 54-6",
    "lat": 37.5641835,
    "lon": 126.9839596
  },
  {
    "id": "naver-restaurant-3b1efe65",
    "name": "하이디라오 명동점",
    "category": "중식",
    "mainMenu": "음식점>중식당",
    "recommendedMenu": "짜장면 또는 짬뽕",
    "lunchPrice": 13000,
    "dinnerPrice": 18000,
    "distanceMeters": 292,
    "walkMinutes": 4,
    "tags": [],
    "goodForLunch": true,
    "goodForDinner": false,
    "groupFriendly": false,
    "alcoholFriendly": false,
    "managerPreferenceScore": 5,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://app.catchtable.co.kr/ct/shop/haidilao_myungdong",
    "roadAddress": "서울특별시 중구 명동3길 36 1층",
    "address": "서울특별시 중구 을지로2가 199-13 1층",
    "lat": 37.5653492,
    "lon": 126.9837511
  },
  {
    "id": "naver-restaurant-9c5f9214",
    "name": "평래옥",
    "category": "한식",
    "mainMenu": "음식점>한식",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 295,
    "walkMinutes": 4,
    "tags": [
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "",
    "roadAddress": "서울특별시 중구 마른내로 21-1",
    "address": "서울특별시 중구 저동2가 18-1",
    "lat": 37.564901,
    "lon": 126.9903879
  },
  {
    "id": "naver-restaurant-adba239b",
    "name": "을지백탄뼈구이",
    "category": "한식",
    "mainMenu": "음식점>한식",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 299,
    "walkMinutes": 4,
    "tags": [
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://www.instagram.com/eulji_baektan",
    "roadAddress": "서울특별시 중구 을지로 110-2 1층",
    "address": "서울특별시 중구 을지로3가 345-6 1층",
    "lat": 37.5660916,
    "lon": 126.9902218
  },
  {
    "id": "naver-restaurant-4a1fd579",
    "name": "쯔루하시 후게츠 명동점",
    "category": "일식/돈까스",
    "mainMenu": "음식점>일식>일식당",
    "recommendedMenu": "덮밥 또는 우동",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 309,
    "walkMinutes": 4,
    "tags": [
      "깔끔함"
    ],
    "goodForLunch": true,
    "goodForDinner": false,
    "groupFriendly": false,
    "alcoholFriendly": false,
    "managerPreferenceScore": 5,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://www.instagram.com/fugetsu__?igsh=MTY2Z3Jlc3V4NXBqNA==",
    "roadAddress": "서울특별시 중구 명동8길 21-5 해암빌딩 2층",
    "address": "서울특별시 중구 명동2가 32-27 해암빌딩 2층",
    "lat": 37.56285,
    "lon": 126.9850447
  },
  {
    "id": "naver-restaurant-ab84a04c",
    "name": "청기와타운 을지로점",
    "category": "한식",
    "mainMenu": "한식>육류,고기요리",
    "recommendedMenu": "고기류 식사",
    "lunchPrice": 16000,
    "dinnerPrice": 30000,
    "distanceMeters": 310,
    "walkMinutes": 4,
    "tags": [
      "술한잔",
      "팀장님취향",
      "한식",
      "회식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": true,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://catchtable.co.kr/bluerooftown5",
    "roadAddress": "서울특별시 중구 을지로 54 1층 청기와타운 을지로점",
    "address": "서울특별시 중구 을지로2가 199-21 1층 청기와타운 을지로점",
    "lat": 37.565902,
    "lon": 126.9836749
  },
  {
    "id": "naver-restaurant-aa505202",
    "name": "효담칼국수 닭한마리 명동본점",
    "category": "한식",
    "mainMenu": "음식점>한식",
    "recommendedMenu": "칼국수와 만두",
    "lunchPrice": 11000,
    "dinnerPrice": 16000,
    "distanceMeters": 317,
    "walkMinutes": 4,
    "tags": [
      "가성비",
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://www.instagram.com/hyodam_dakkal",
    "roadAddress": "서울특별시 중구 명동3길 12 B1층",
    "address": "서울특별시 중구 명동1가 59-25 B1층",
    "lat": 37.5642444,
    "lon": 126.983632
  },
  {
    "id": "naver-restaurant-80df8089",
    "name": "딘타이펑 명동점",
    "category": "중식",
    "mainMenu": "음식점>중식당",
    "recommendedMenu": "짜장면 또는 짬뽕",
    "lunchPrice": 13000,
    "dinnerPrice": 18000,
    "distanceMeters": 318,
    "walkMinutes": 4,
    "tags": [],
    "goodForLunch": true,
    "goodForDinner": false,
    "groupFriendly": false,
    "alcoholFriendly": false,
    "managerPreferenceScore": 5,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "http://www.dintaifung.co.kr/",
    "roadAddress": "서울특별시 중구 명동7길 13 호텔28 2층",
    "address": "서울특별시 중구 명동1가 59-1 호텔28 2층",
    "lat": 37.5643367,
    "lon": 126.9835899
  },
  {
    "id": "naver-restaurant-c2cb1821",
    "name": "산청숯불가든 을지로",
    "category": "한식",
    "mainMenu": "한식>육류,고기요리",
    "recommendedMenu": "고기류 식사",
    "lunchPrice": 16000,
    "dinnerPrice": 30000,
    "distanceMeters": 324,
    "walkMinutes": 4,
    "tags": [
      "술한잔",
      "팀장님취향",
      "한식",
      "회식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": true,
    "managerPreferenceScore": 8,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://www.instagram.com/sancheongin/",
    "roadAddress": "서울특별시 중구 을지로 114-6 1층",
    "address": "서울특별시 중구 을지로3가 343-1 1층",
    "lat": 37.5658389,
    "lon": 126.9906186
  },
  {
    "id": "naver-restaurant-7d6ce55c",
    "name": "명동돈가스",
    "category": "일식/돈까스",
    "mainMenu": "음식점>일식>돈가스",
    "recommendedMenu": "돈가스 정식",
    "lunchPrice": 13000,
    "dinnerPrice": 18000,
    "distanceMeters": 332,
    "walkMinutes": 4,
    "tags": [
      "깔끔함"
    ],
    "goodForLunch": true,
    "goodForDinner": false,
    "groupFriendly": false,
    "alcoholFriendly": false,
    "managerPreferenceScore": 5,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "http://mddongas.co.kr/",
    "roadAddress": "서울특별시 중구 명동3길 8",
    "address": "서울특별시 중구 명동1가 59-13",
    "lat": 37.5640263,
    "lon": 126.983556
  },
  {
    "id": "naver-restaurant-782b0bfa",
    "name": "고씨네고추장찌개",
    "category": "한식",
    "mainMenu": "음식점>한식",
    "recommendedMenu": "찌개 정식",
    "lunchPrice": 11000,
    "dinnerPrice": 16000,
    "distanceMeters": 342,
    "walkMinutes": 5,
    "tags": [
      "가성비",
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 10,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://instagram.com/kohouse2020?igshid=48jca2p3p4ej",
    "roadAddress": "서울특별시 중구 수표로 26 1층",
    "address": "서울특별시 중구 저동2가 48-7 1층",
    "lat": 37.5635255,
    "lon": 126.9903747
  },
  {
    "id": "naver-restaurant-3f2886a2",
    "name": "진중 우육면관 본점",
    "category": "아시아음식",
    "mainMenu": "음식점>아시아음식",
    "recommendedMenu": "대표 식사 메뉴",
    "lunchPrice": 13000,
    "dinnerPrice": 22000,
    "distanceMeters": 384,
    "walkMinutes": 5,
    "tags": [],
    "goodForLunch": true,
    "goodForDinner": false,
    "groupFriendly": false,
    "alcoholFriendly": false,
    "managerPreferenceScore": 4,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "https://app.catchtable.co.kr/ct/shop/niuroumianguan",
    "roadAddress": "서울특별시 종로구 청계천로 75-2 진중 우육면관 본점 (Niuroumianguan)",
    "address": "서울특별시 종로구 관철동 11-11 진중 우육면관 본점 (Niuroumianguan)",
    "lat": 37.5685164,
    "lon": 126.9862478
  },
  {
    "id": "naver-restaurant-fec38fbb",
    "name": "서울뚝배기",
    "category": "한식",
    "mainMenu": "한식>찌개,전골",
    "recommendedMenu": "찌개 정식",
    "lunchPrice": 11000,
    "dinnerPrice": 16000,
    "distanceMeters": 397,
    "walkMinutes": 5,
    "tags": [
      "가성비",
      "팀장님취향",
      "한식"
    ],
    "goodForLunch": true,
    "goodForDinner": true,
    "groupFriendly": true,
    "alcoholFriendly": false,
    "managerPreferenceScore": 10,
    "notes": "네이버 지역검색에서 자동 수집했습니다. 가격·메뉴·회식 적합도는 카테고리 기반 추정값이므로 운영 전 확인하세요.",
    "lastVisitedDate": null,
    "dislike": false,
    "favorite": false,
    "source": "naver-local-search",
    "naverLink": "",
    "roadAddress": "서울특별시 중구 수표로6길 1 금용빌딩",
    "address": "서울특별시 중구 충무로3가 24-11 금용빌딩",
    "lat": 37.5628737,
    "lon": 126.9905541
  }
];
